//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: comment.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Comment_CommentServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Comment_CommentServiceService {
  func getComment(_ request: Comment_Filter, callOptions: CallOptions?, handler: @escaping (Comment_Comment) -> Void) -> ServerStreamingCall<Comment_Filter, Comment_Comment>
}

internal final class Comment_CommentServiceServiceClient: GRPCClient, Comment_CommentServiceService {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the comment.CommentService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous server-streaming call to GetComment.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetComment.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func getComment(_ request: Comment_Filter, callOptions: CallOptions? = nil, handler: @escaping (Comment_Comment) -> Void) -> ServerStreamingCall<Comment_Filter, Comment_Comment> {
    return self.makeServerStreamingCall(path: "/comment.CommentService/GetComment",
                                        request: request,
                                        callOptions: callOptions ?? self.defaultCallOptions,
                                        handler: handler)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Comment_CommentServiceProvider: CallHandlerProvider {
  func getComment(request: Comment_Filter, context: StreamingResponseCallContext<Comment_Comment>) -> EventLoopFuture<GRPCStatus>
}

extension Comment_CommentServiceProvider {
  internal var serviceName: String { return "comment.CommentService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "GetComment":
      return ServerStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.getComment(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


/// Provides conformance to `GRPCPayload` for the request and response messages
extension Comment_Filter: GRPCProtobufPayload {}
extension Comment_Comment: GRPCProtobufPayload {}

